### ISSUE TITLE
Google Maps API 3 and metor-famous-views

### ISSUE THREAD

**Issue by MiMaMuh** [gadicc/meteor-famous-views#200]
Hi, 

I've tried to add a map with Google Maps JavaScript API 3 within a surface but it seems it's a bit buggy. I don't know what's the problem. I've read some issues here and there but I don't get it. The first time the map loads fine, but when I've route from some page back to the map-page with iron-router the map don't render correctly. Is there a special way to treat it? I'm new to famo.us so I don't know where the issue could come from. Any idea?

For example I'm asking myself what makes this extension https://github.com/IjzerenHein/famous-map different from just loading the map into a surface? Do I need it to get a google-maps run with famous-views? Is there any simple solution to integrate a map with famous-views?

Sorry, that are a lot of questions but maybe I just need a simple answer to get the point, I'm stuck right now. Thx.

**Comment by gadicc** [comment]
Hey, sorry for the late reply, been away without internet for the holidays and am slowly catching up.

I haven't tried it myself, but loading a map in a regular Surface should work fine.  Google Maps can be quite tricky though, especially when routing is involved.  Have you tested your code (gmaps + routing) in a Meteor app without Famo.us?  If you haven't already, I suggest getting that working first and then adding the famo.us/surface support later.  Also, if you're using famous-views v0.1.30, try also v0.1.29 (or v0.1.31-pre.1), since the behaviour of the `rendered` callback was a bit buggy in v0.1.30 (#199).

Otherwise, although I also haven't used it yet, I suspect @IjzerenHein's extension offers a smoother experience for using maps on Famo.us.  I see he's also added support for panning and synchronization with modifier events, so definitely for any fancy famo.us stuff with maps, this is the route you'll want to go.  However, you'll need to get it working in famous yourself since no one has made a plugin for it yet.  Also, as said, it's not "required" and may be easier to get normal maps working first.

Lastly, as someone who has used both Google Maps and Leaflet, if you don't need any particular Google Maps features, I'd recommend Leaflet.  It's open source, smaller, and works better on mobile.

**Comment by der-ede** [comment]
Hi there,

just attaching my question here, please tell me if I should open a new issue for this.
I am trying to get famous-views working not with Google Maps but with Openlayers 3, because I need the rotation functionality.
Any ideas how to do that?

Regards
