### ISSUE TITLE
Iron Router Transition

### ISSUE THREAD

**Issue by athenawisdoms** [gadicc/meteor-famous-views#202]
Is it possible to set `fview._transitionModifierOnce` to have no transition? My code below does not succeed at it.

	if(fview) {
		fview._transitionModifierOnce = ''"
	}

**Comment by trusktr** [comment]
Is it because you have an extra quote in there?

**Comment by gadicc** [comment]
Glad to see you back!  Sorry for late reply, been away without internet, slowly catching up.

Just to double check, you want to disable the transition once off - for a single change - right?

Does `fview._transitionOnce = null` work?

**Comment by typ90** [comment]
What would be the difficulty level of allowing users to specify custom transitions / transition modifiers here? Are `FView.transitionModifiers` only defined in the RenderController.js view?

**Comment by gadicc** [comment]
I've been meaning to clean this up a bit and provide a proper method to add custom transitions, but for now, just realize that `FView.transitionModifiers` is public, so it's no problem to do:

```js
FView.transitionModifiers.myCustomTransition = {
    outOpacityFrom: function(progress) { return 1; },
    inOpacityFrom: function(progress) { return 1; },
    outTransormFrom: function(progress) { return Transform.Identity; },
    inTransformFrom: function(progress) { return Transform.Identity; }
};
```

It's important to specify all four otherwise the previous functions will still be present (I guess we should actually handle that automatically... TODO).

**Comment by trusktr** [comment]
@gadicc Is fview.transitionModifiers in the docs? If not, could you give a tiny usage example. :D

**Comment by gadicc** [comment]
Mmm, I thought it was in http://famous-views.meteor.com/views/RenderController but I guess not :(  It's only used by RenderController though.  By default you shouldn't really need to use it directly, since the reactive `transition=` argument to the RenderController template will set it for you.  So with the code snippet above, you could do:

```jade
+RenderController transition="myCustomTransition"
```

and it would all work without any extra code in the middle.  Setting `transitionModifierOnce` (for a once off transition) is a little more complicated, but that is documented on that page, and that really is something you'd use JS for.

Hope that's all clear.  I agree the API is not ideal hence the new issue ref'd above ("clean up custom transitions").

**Comment by gadicc** [comment]
I'm closing this and will track in https://github.com/gadicc/meteor-famous-views/issues/193.
